fixed installation in virtual env

diff --git a/bin/ck b/bin/ck
--- a/bin/ck
+++ b/bin/ck
@@ -51,12 +51,16 @@ if [ "$CK_ROOT" == "" ]; then
 fi
 
 if [ ! -f "$CK_ROOT/ck/kernel.py" ]; then 
-   echo ""
-   echo "CK installation problem: can't find ck/kernel.py in CK_ROOT!"
-   echo "Detected CK_ROOT: ${CK_ROOT}"
-   echo "Please report this problem at https://github.com/ctuning/ck/issues"
-   echo ""
-   exit 1
+#   echo ""
+#   echo "CK installation problem: can't find ck/kernel.py in CK_ROOT!"
+#   echo "Detected CK_ROOT: ${CK_ROOT}"
+#   echo "Please report this problem at https://github.com/ctuning/ck/issues"
+#   echo ""
+#   exit 1
+# Attempt to run directly (usually venv)
+
+   $CK_PYTHON -W ignore::RuntimeWarning -m ck.kernel "$@"
+else
+   $CK_PYTHON -W ignore::DeprecationWarning $CK_ROOT/ck/kernel.py "$@"
 fi
 
-$CK_PYTHON -W ignore::DeprecationWarning $CK_ROOT/ck/kernel.py "$@"
